# Generated by Django 5.0.4 on 2026-04-11 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RichContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField(blank=True, default='', help_text='Main text content (HTML allowed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rich_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('youtube', 'YouTube')], default='text', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content_text', models.TextField(blank=True, default='', help_text='Rich text content')),
                ('media_url', models.URLField(blank=True, default='', help_text='URL for video/audio/image')),
                ('media_file', models.FileField(blank=True, help_text='Upload audio/video/image file', null=True, upload_to='media_blocks/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rich_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_blocks', to='courses.richcontent')),
            ],
            options={
                'ordering': ['rich_content', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HighlightedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('language', models.CharField(default='bn', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rich_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='courses.richcontent')),
            ],
            options={
                'ordering': ['rich_content', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AccordionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('rich_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_sections', to='courses.richcontent')),
            ],
            options={
                'ordering': ['rich_content', 'order'],
            },
        ),
    ]
