# Generated by Django 5.0.4 on 2026-04-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermMediaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('youtube', 'YouTube')], default='text', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content_text', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, default='')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='term_media/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_blocks', to='courses.highlightedterm')),
            ],
            options={
                'ordering': ['term', 'order'],
            },
        ),
    ]
